name: Tickets
main: za.net.quantumsicarius.tickets.Tickets
version: 0.0.7
depend: [Spout]
load: startup
authors: [Quantum-Sicarius,Guy_de_Siguro]
commands:
   ticket:
      description: Shows the ticket help page
      usage: /<command> <param> <param>

permissions:
   tickets.*:
     description: Gives access to all tickets commands
     children:
        tickets.new : true
        tickets.view : true
        tickets.highpriority : true
        tickets.modlist : true
        tickets.reload : true
   tickets.new:
     description: Gives you access to create a new ticket
     defualt: true
   tickets.view:
     description: Gives you access to view tickets
     defualt: op
   tickets.highpriority:
     description: Gives the player extra priority when they create a ticket
     defualt: op
   tickets.reload:
     description: Reloads the plugins config
     defualt: op
   tickets.modlist:
     description: Gives you access to view the modlist
     defualt: op
